{
  "formatVersion": "1.1",
  "component": {
    "group": "net.andrewthepika",
    "module": "Minefinity",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Minefinity-1.0-SNAPSHOT.jar",
          "url": "Minefinity-1.0-SNAPSHOT.jar",
          "size": 30734,
          "sha512": "3d4453a7abdbb3cd05465e35956056c94ff368691c4f42512b7384cdfbd8501247778f5fc4a3218bd71aa0a6461ddd10ca05eb504a0fc2b3e5ea72da9f4a5f1f",
          "sha256": "6b192e69a3fe70ebc6b11fe9667bf7cb080b469dc2c85cc0b82011ba94d9143c",
          "sha1": "f8434db93ecba99827ee24fda8723764aa28eefa",
          "md5": "f85328fe6dc5e22456d596dee4f439f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Minefinity-1.0-SNAPSHOT.jar",
          "url": "Minefinity-1.0-SNAPSHOT.jar",
          "size": 30734,
          "sha512": "3d4453a7abdbb3cd05465e35956056c94ff368691c4f42512b7384cdfbd8501247778f5fc4a3218bd71aa0a6461ddd10ca05eb504a0fc2b3e5ea72da9f4a5f1f",
          "sha256": "6b192e69a3fe70ebc6b11fe9667bf7cb080b469dc2c85cc0b82011ba94d9143c",
          "sha1": "f8434db93ecba99827ee24fda8723764aa28eefa",
          "md5": "f85328fe6dc5e22456d596dee4f439f5"
        }
      ]
    }
  ]
}
